apiVersion: batch/v1
kind: Job
metadata:
  name: smc-metadata
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: smc-metadata
          image: busybox:1.28
          command: ["sh", "-c"]
          args:
            - cat  /opt/smc/metadata.sql
          volumeMounts:
            - name: smc-metadata-sql
              mountPath: /opt/smc
      restartPolicy: Never
      volumes:
        - name: smc-metadata-sql
          configMap:
            name: smc-metadata-sql-3
  backoffLimit: 3
